#!/bin/bash
# Cache the file for 30 minutes
# If you want to override this, put the command in cron.
# We cache because it is a 1sec delay, which is painful for the poller

rpm=$(command -v rpm)

if [[ -x $rpm ]]; then
    DATE=$(date +%s)
    FILE=/tmp/observium-agent-rpm

    NEED_UPDATE=0
    if [[ ! -e "$FILE" ]]; then
        NEED_UPDATE=1
    else
        FILEMTIME=$(stat -c %Y "$FILE")
        FILEAGE=$(($DATE-$FILEMTIME))
        if [[ $FILEAGE -gt 1800 ]]; then
            NEED_UPDATE=1
        fi
    fi

    if [[ $NEED_UPDATE -eq 1 ]]; then
        $rpm -q --all --queryformat '%{N} %{V} %{R} %{ARCH} %{SIZE}\n' > "$FILE"
    fi

    echo "<<<rpm>>>"
    cat "$FILE"
fi